export const STORAGE_URL = import.meta.env.VITE_STORAGE_URL || "/storage";
export const IMAGE_CDN_URL = import.meta.env.VITE_IMAGE_CDN_URL || "";
export const IMAGE_CDN_FALLBACK = import.meta.env.VITE_IMAGE_CDN_FALLBACK || "";
export const IMAGE_BASE_URL = IMAGE_CDN_URL || STORAGE_URL;

// Use API origin for storage when frontend is on a different port
const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000/api";
const API_ORIGIN = API_URL.replace(/\/api\/?$/, "");

export const PLACEHOLDER_RESTAURANT = "/placeholder-restaurant.svg";
export const PLACEHOLDER_LOGO = "/placeholder-logo.svg";
export const PLACEHOLDER_AVATAR = "/placeholder-avatar.svg";

const failedUrls = new Set<string>();

export function resolveImageUrl(path?: string | null): string | null {
  if (!path) return null;
  if (path.startsWith("blob:")) return path;
  if (path.startsWith("http://") || path.startsWith("https://")) {
    if (failedUrls.has(path) && IMAGE_CDN_FALLBACK) {
      const fallbackPath = path.replace(IMAGE_CDN_URL, IMAGE_CDN_FALLBACK);
      if (fallbackPath !== path) return fallbackPath;
    }
    return path;
  }
  const clean = path.startsWith("/") ? path.slice(1) : path;
  if (IMAGE_CDN_URL) {
    const cdnUrl = `${IMAGE_CDN_URL}/${clean}`;
    if (!failedUrls.has(cdnUrl)) return cdnUrl;
    if (IMAGE_CDN_FALLBACK) return `${IMAGE_CDN_FALLBACK}/${clean}`;
  }
  // If STORAGE_URL is relative and API is on different origin, use API origin
  if (STORAGE_URL.startsWith("/") && API_ORIGIN) {
    return `${API_ORIGIN}${STORAGE_URL}/${clean}`;
  }
  return `${STORAGE_URL}/${clean}`;
}

export const getImageUrl = resolveImageUrl;

export function markUrlFailed(url: string): void {
  failedUrls.add(url);
  if (failedUrls.size > 100) {
    const first = failedUrls.values().next().value;
    if (first) failedUrls.delete(first);
  }
}

export function handleImageError(e: React.SyntheticEvent<HTMLImageElement>, fallback?: string) {
  const img = e.target as HTMLImageElement;
  markUrlFailed(img.src);
  if (!img.dataset.fallbackAttempted) {
    img.dataset.fallbackAttempted = "true";
    const newSrc = fallback || PLACEHOLDER_RESTAURANT;
    if (newSrc !== img.src) img.src = newSrc;
  }
}

export function getImageUrlWithVersion(path?: string | null, version?: string | number | null): string | null {
  const url = resolveImageUrl(path);
  if (!url || !version) return url;
  const sep = url.includes("?") ? "&" : "?";
  return `${url}${sep}v=${version}`;
}

/**
 * Get a variant URL from an original image path.
 * Variants are generated by ImageVariantService at upload time.
 * Falls back to original if variant doesn't exist.
 *
 * Example:
 *   path: "restaurantes/8/portada/uuid.jpg"
 *   variant: "640"
 *   → "/storage/restaurantes/8/portada/640/uuid.webp"
 */
export function getImageVariantUrl(path: string | null | undefined, variant?: string): string | null {
  if (!path) return null;
  const dir = path.substring(0, path.lastIndexOf("/"));
  const file = path.substring(path.lastIndexOf("/") + 1);
  const name = file.replace(/\.[^.]+$/, "");
  if (variant) {
    return resolveImageUrl(`${dir}/${variant}/${name}.webp`);
  }
  return resolveImageUrl(path);
}

/** Predefined variant sizes matching ImageVariantService */
export const HERO_DESKTOP = "1280";
export const HERO_MOBILE = "640";
export const GALLERY_THUMB = "thumb";
export const GALLERY_MEDIUM = "medium";
export const CARD_VARIANT = "640";
export const LOGO_SIDEBAR = "128";
export const LOGO_NAVBAR = "256";
